# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCEIaV2pCO9wD--oA1T7qnxPRAZQGgXe

Пример кода на Python для A/B-тестирования
"""

import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

# Пример данных
data = {
    'group': ['A'] * 50 + ['B'] * 50,  # 50 человек в контрольной и 50 в тестовой группе
    'satisfaction_score': np.random.normal(70, 10, 50).tolist() + np.random.normal(75, 10, 50).tolist(),
    'performance_score': np.random.normal(80, 15, 50).tolist() + np.random.normal(85, 15, 50).tolist()
}

# Создаем DataFrame
df = pd.DataFrame(data)

# Разделение на контрольную и тестовую группы
group_A = df[df['group'] == 'A']
group_B = df[df['group'] == 'B']

# 1. Сравнение уровня удовлетворенности пациентов
t_stat, p_val_satisfaction = stats.ttest_ind(group_A['satisfaction_score'], group_B['satisfaction_score'])

# 2. Сравнение производительности сотрудников
t_stat, p_val_performance = stats.ttest_ind(group_A['performance_score'], group_B['performance_score'])

# Вывод результатов
print(f"Уровень удовлетворенности пациентов:")
print(f"T-статистика: {t_stat:.2f}, p-значение: {p_val_satisfaction:.4f}")
if p_val_satisfaction < 0.05:
    print("Различие значимо: внедрение DISC оказывает влияние на удовлетворенность пациентов.")
else:
    print("Различие незначимо: внедрение DISC не оказывает заметного влияния на удовлетворенность пациентов.")

print(f"\nПроизводительность сотрудников:")
print(f"T-статистика: {t_stat:.2f}, p-значение: {p_val_performance:.4f}")
if p_val_performance < 0.05:
    print("Различие значимо: внедрение DISC оказывает влияние на производительность сотрудников.")
else:
    print("Различие незначимо: внедрение DISC не оказывает заметного влияния на производительность сотрудников.")

# Визуализация распределения оценок
plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.hist(group_A['satisfaction_score'], alpha=0.7, label='Группа A (контроль)')
plt.hist(group_B['satisfaction_score'], alpha=0.7, label='Группа B (тест)')
plt.title("Уровень удовлетворенности пациентов")
plt.xlabel("Оценка удовлетворенности")
plt.ylabel("Количество")
plt.legend()

plt.subplot(1, 2, 2)
plt.hist(group_A['performance_score'], alpha=0.7, label='Группа A (контроль)')
plt.hist(group_B['performance_score'], alpha=0.7, label='Группа B (тест)')
plt.title("Производительность сотрудников")
plt.xlabel("Оценка производительности")
plt.ylabel("Количество")
plt.legend()

plt.tight_layout()
plt.show()