# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PM7WI0UBVosI4Eg61GqsbX_Zx300ZSl2

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Параметры моделирования
num_patients = 100  # количество пациентов
np.random.seed(42)

# Время обработки запроса (в минутах) до внедрения DISC
time_before_DISC = np.random.normal(loc=20, scale=5, size=num_patients)

# Время обработки запроса после внедрения DISC
# Ожидаем, что внедрение DISC снижает среднее время обработки запросов
time_after_DISC = np.random.normal(loc=15, scale=5, size=num_patients)

# Создаем DataFrame для удобства анализа
data = pd.DataFrame({
    'Patient_ID': range(1, num_patients + 1),
    'Time_Before_DISC': time_before_DISC,
    'Time_After_DISC': time_after_DISC
})

# Рассчитываем среднее время отклика до и после внедрения DISC
mean_time_before = np.mean(data['Time_Before_DISC'])
mean_time_after = np.mean(data['Time_After_DISC'])

print(f"Среднее время обработки запроса до внедрения DISC: {mean_time_before:.2f} минут")
print(f"Среднее время обработки запроса после внедрения DISC: {mean_time_after:.2f} минут")

# Визуализация результатов
plt.figure(figsize=(12, 6))
plt.hist(data['Time_Before_DISC'], bins=15, alpha=0.7, label='До внедрения DISC')
plt.hist(data['Time_After_DISC'], bins=15, alpha=0.7, label='После внедрения DISC')
plt.title("Время обработки запросов пациентов до и после внедрения DISC")
plt.xlabel("Время обработки (минуты)")
plt.ylabel("Количество пациентов")
plt.legend()
plt.show()

# Анализ различий с использованием статистического теста
t_stat, p_val = stats.ttest_ind(data['Time_Before_DISC'], data['Time_After_DISC'])
print(f"\nРезультат t-теста для времени обработки запросов:")
print(f"T-статистика: {t_stat:.2f}, p-значение: {p_val:.4f}")
if p_val < 0.05:
    print("Различие значимо: внедрение DISC снижает время обработки запросов пациентов.")
else:
    print("Различие незначимо: внедрение DISC не оказывает заметного влияния на время обработки запросов.")